import Navbar from "@/components/navbar";
import type { Metadata } from "next";
import { Anton } from "next/font/google";

import Footer from "@/components/footer";
import "./globals.css";

const anton = Anton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton",
});

export const metadata: Metadata = {
  title: "PCFC Connect Group",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="globals.css" />
      </head>
      <body
        className={`${anton.variable} w-full antialiased bg-contain bg-[url(/bg-vertical.jpg)]`}
      >
        <Navbar />
        <div className="flex w-full py-8 justify-center overflow-hidden md:mb-32">
          <div className="z-5 shadow-md rounded-2xl ">{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
