"use server";

import { Leader } from "@/lib/types/leader";

export async function getLeaders(): Promise<Leader[]> {
  const groupLeaders: Leader[] = [
    {
      name: "Rose Carandang",
      day: "Saturday",
      time: "2PM",
      isOnline: false,
      location: "Church",
    },
    {
      name: "Juliet Guinto",
      day: "Thursday",
      time: "Evening",
      isOnline: true,
      location: "Zoom",
    },
    {
      name: "Jasmin Gines-Japa",
      day: "Wednesday",
      time: "7:30PM",
      isOnline: true,
      location: "Zoom",
    },
    {
      name: "Joy Manlupig",
      day: "Sunday",
      time: "After Service",
      isOnline: false,
      location: "Church",
    },
    {
      name: "Jojo Tagarda",
      day: "Sunday",
      time: "After Service",
      isOnline: false,
      location: "Church",
    },
    {
      name: "Jocelyn Bensan",
      day: "Weekdays",
      time: "Afternoon",
      isOnline: true,
      location: "Zoom",
    },
    {
      name: "Riza Dizon",
      day: "Sunday",
      time: "3PM",
      isOnline: false,
      location: "Home-based",
    },
    {
      name: "Omer Dizon",
      day: "Saturday",
      time: "9PM",
      isOnline: false,
      location: "Home-based",
    },
    {
      name: "Juvy Kalaw",
      day: "Friday",
      time: "8:30PM",
      isOnline: true,
      location: "Zoom",
    },
    {
      name: "Gerry Kalaw",
      day: "Saturday",
      time: "7:30PM",
      isOnline: true,
      location: "Zoom",
    },
    {
      name: "Cyrus Gonzalo",
      day: "Saturday",
      time: "Afternoon",
      isOnline: false,
      location: "Home-based",
    },
    {
      name: "Lourdes Galaang",
      day: "Tuesday",
      time: "7:30PM",
      isOnline: true,
      location: "Virtual",
    },
    {
      name: "Rodel Valledor",
      day: "Friday",
      time: "7:30PM",
      isOnline: true,
      location: "Zoom",
    },
    {
      name: "Mark Namnama",
      day: "Friday",
      time: "7PM",
      isOnline: true,
      location: "Zoom",
    },
    {
      name: "Jamil Namnama",
      day: "Weekdays",
      time: "Evening",
      isOnline: true,
      location: "Zoom",
    },
    {
      name: "May Soriano",
      day: "Saturday",
      time: "6PM",
      isOnline: false,
      location: "Home-based",
    },
    {
      name: "Kheana Quiddaeon",
      day: "Thursday",
      time: "7PM",
      isOnline: true,
      location: "Zoom",
    },
    {
      name: "Maery Bagay",
      day: "Saturday",
      time: "7:30PM",
      isOnline: true,
      location: "Zoom",
    },
    {
      name: "Venna Domingsil",
      day: "Weekdays",
      time: "Evening",
      isOnline: true,
      location: "Zoom",
    },
    {
      name: "Paz Virrey",
      day: "Thursday",
      time: "8PM",
      isOnline: true,
      location: "Zoom",
    },
    {
      name: "Allan Virrey",
      day: "Thursday",
      time: "8PM",
      isOnline: true,
      location: "Zoom",
    },
    {
      name: "Stanley Esquierdo",
      day: "Tuesday",
      time: "7PM",
      isOnline: true,
      location: "Discord",
    },
    {
      name: "Mercy Cusilit",
      day: "Weekend",
      time: "4PM",
      isOnline: false,
      location: "Home-based",
    },
    {
      name: "Via Manuel",
      day: "Tuesday",
      time: "7PM",
      isOnline: true,
      location: "Zoom",
    },
    {
      name: "Jun Esquierdo",
      day: "Friday",
      time: "8:30PM",
      isOnline: true,
      location: "Zoom",
    },
    {
      name: "Ana Mae Duca",
      day: "Weekdays",
      time: "Morning",
      isOnline: true,
      location: "Zoom",
    },
    {
      name: "Wilma Aurellio",
      day: "Weekdays",
      time: "Evening",
      isOnline: true,
      location: "Zoom",
    },
    {
      name: "Reli Guiterrez",
      day: "Saturday",
      time: "2PM",
      isOnline: false,
      location: "Church",
    },
    {
      name: "Bong",
      day: "Weekdays",
      time: "Evening",
      isOnline: true,
      location: "Virtual",
    },
  ];

  return groupLeaders;
}
